# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_2026',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/nbdev_2026',
                'lib_path': 'nbdev_2026'},
  'syms': {'nbdev_2026.core': {'nbdev_2026.core.foo': ('core.html#foo', 'nbdev_2026/core.py')}}}
