"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['saludo', 'saludo_a']

# %% ../nbs/00_core.ipynb #8824dc16
def saludo():
    """Imprime Hola"""
    print('Hola!')
    return

# %% ../nbs/00_core.ipynb #1fe79e7c
def saludo_a(to):
    """Imprime hola a un nombre"""
    print('Hola!', to)
    
    print('Espero que te encuentres bien')
    return
